apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-python
spec:
    replicas: 3
    selector:
        matchLabels:
            app: tf-python
    template:
        metadata:
            labels:
                app: tf-python
        spec:
            containers:
            - name: tf-python
              image: jmitchel3/tf-python:latest
              ports:
                - containerPort: 8080
              env:
                - name: PORT
                  value: "8080"
                # - name: ENV_MESSAGE
                #   valueFrom:
                #     configMapKeyRef:
                #       name: tf-python-cm
                #       key: ENV_MESSAGE
                - name: SECRET_MESSAGE
                  valueFrom:
                    secretKeyRef:
                      name: tf-python-secret
                      key: SECRET_MESSAGE
              envFrom:
                - configMapKeyRef:
                  name: tf-python-cm



